# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9da23855b4ff23521841b2d332cfb987873c603cc774ab599af8c8d17250f4d7751c0b43d0b6416de39b5f80b8c6a971be9f264a79f350d702cb8b0d23794902

test:
  secret_key_base: 11683cca617c20abcd6a4c5b3cf20470e0dd783fcd846fb9b3e356850548e2a18329f50555cb9d6d1c94162c7c2a9a62f57436432a33ecdd4f5b297f45c34289

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
